printSYZ()
{
	printf("此处为函数gcd声明!\n");
	printf("函数的变量u的声明!\n");
	printf("函数的变量v的声明!\n");printf("203 j==  v  0 205\n");
	printf("204 j    -   -  T\n");
	printf("205 j( g u T\n");
	printf("206 j= T - e\n");
	printf("207 j) 1 ; T\n");
	printf("208 j= T - v\n");
	printf("此处为函数main部分!\n");
	printf("函数的变量x的声明!\n");
	printf("函数的变量y的声明!\n");
	printf("212 j( i ) T\n");
	printf("213 j= T - x\n");
	printf("214 j( i ) T\n");
	printf("215 j= T - y\n");
	printf("216 j( g x T\n");
	printf("217 j= T - o\n");
	printf("218 j; ) } T\n");
	printf("219 j= T - y\n");
}
